export const subjectList = [
    { value: 'Accounting' },
    { value: 'Anthropology' },
    { value: 'Art History' },
    { value: 'Astronomy' },
    { value: 'Biology' },
    { value: 'Business Administration' },
    { value: 'Chemistry' },
    { value: 'Communications' },
    { value: 'Computer Science' },
    { value: 'Creative Writing' },
    { value: 'Criminal Justice' },
    { value: 'Digital Media' },
    { value: 'Economics' },
    { value: 'Education' },
    { value: 'Engineering' },
    { value: 'English' },
    { value: 'English Literature' },
    { value: 'Environmental Science' },
    { value: 'Film Studies' },
    { value: 'French' },
    { value: 'Geography' },
    { value: 'Global Studies' },
    { value: 'History' },
    { value: 'International Relations' },
    { value: 'Journalism' },
    { value: 'Law' },
    { value: 'Linguistics' },
    { value: 'Marketing' },
    { value: 'Mathematics' },
    { value: 'Mechanical Engineering' },
    { value: 'Music' },
    { value: 'Neuroscience' },
    { value: 'Philosophy' },
    { value: 'Physics' },
    { value: 'Political Science' },
    { value: 'Psychology' },
    { value: 'Public Health' },
    { value: 'Religious Studies' },
    { value: 'Social Work' },
    { value: 'Sociology' },
    { value: 'Spanish' },
    { value: 'Statistics' },
    { value: 'Sustainability Studies' },
    { value: 'Theater' },
    { value: 'Theology' },
    { value: 'Urban Studies' },
    { value: 'Visual Arts' },
    { value: 'Womens Studies' }
  ];
  